## Teste arruma_sa

test_that("testa todos os tipos e posiçoes de 's/a'.", {
  expect_equal(arruma_sa("aymore credito financiamento e investimento s.a"), "aymore credito financiamento e investimento @s@a@")
  expect_equal(arruma_sa('banco itau s.a.'), 'banco itau @s@a@')
  expect_equal(arruma_sa('banco finasa bmc s a'), "banco finasa bmc @s@a@")
  expect_equal(arruma_sa('aymore credito financiamento e investimento sa'), 'aymore credito financiamento e investimento @s@a@')
  expect_equal(arruma_sa('ampla energia e servicos s.a. (ampla)'), 'ampla energia e servicos @s@a@ (ampla)')
  expect_equal(arruma_sa('banco finasa bmc s/a'), 'banco finasa bmc @s@a@')
  expect_equal(arruma_sa('bradesco leasing s/a arrendamento mercantil'), 'bradesco leasing @s@a@ arrendamento mercantil')
  expect_equal(arruma_sa('light servicos de eletricidade s a'), 'light servicos de eletricidade @s@a@')
  expect_equal(arruma_sa('telemar norte leste s.a.'), 'telemar norte leste @s@a@')
  expect_equal(arruma_sa('light servicos de eletricidade s.a.'), 'light servicos de eletricidade @s@a@')
  expect_equal(arruma_sa('telemar norte leste s a'), 'telemar norte leste @s@a@')
  expect_equal(arruma_sa('sociedade de ensino superior estacio de sa'), 'sociedade de ensino superior estacio de @s@a@')
  expect_equal(arruma_sa('telemar norte leste sa'), 'telemar norte leste @s@a@')
  expect_equal(arruma_sa('light servicos de eletricidade sa'), 'light servicos de eletricidade @s@a@')
  expect_equal(arruma_sa('bv financeira s a credito financiamento e investimento'), 'bv financeira @s@a@ credito financiamento e investimento')
  expect_equal(arruma_sa('bv financeira sa credito financiamento e investimento'), 'bv financeira @s@a@ credito financiamento e investimento')
  expect_equal(arruma_sa('oi telemar norte leste s. a.'), 'oi telemar norte leste @s@a@')
  expect_equal(arruma_sa('oi telemar norte leste s.a ( oi velox )'), 'oi telemar norte leste @s@a@ ( oi velox )')
  expect_equal(arruma_sa('stemac s a grupos geradores'), 'stemac @s@a@ grupos geradores')
  expect_equal(arruma_sa('todeschini s.a. industria e comercio'), 'todeschini @s@a@ industria e comercio')
  expect_equal(arruma_sa('uniao de lojas leader s.a - leader magazine'), 'uniao de lojas leader @s@a@ - leader magazine')
  expect_equal(arruma_sa('uniao transporte interestadual de luxo s a util'), 'uniao transporte interestadual de luxo @s@a@ util')
  expect_equal(arruma_sa('via varejo s/ a'), 'via varejo @s@a@')
  expect_equal(arruma_sa('vrg linhas aereas sa - gol'), 'vrg linhas aereas @s@a@ - gol')
  expect_equal(arruma_sa('vrg linhas aereas @s@a@ grupo gol'), 'vrg linhas aereas @s@a@ grupo gol')
  expect_equal(arruma_sa('air france s.a.'), 'air france @s@a@')
  expect_equal(arruma_sa('auto pista fluminense s.a'), 'auto pista fluminense @s@a@')
  expect_equal(arruma_sa('banco cruzeiro do sul s a em liquidacao extrajudicial'), 'banco cruzeiro do sul @s@a@ em liquidacao extrajudicial')
})

test_that("testa os casos em que nao deveria fazer nada", {
  nao_faz_nada <- c('helio de jesus sa', 'pedro henrique dos santos sa', 'neusa freitas da rocha bastos', 'maria da ascencao teixeira bessa', 'daniele geri de sousa', 'ana leyla santos','banco santander ( brasil )', 'banco bradesco (finasa)', "sandra de sa", "sandra anemberd", "samanta barbosa dos santos","sassaricando", "sas é uma merda e r é bom", "sasa", "sassas", "salome dos santos", "soap")
  expect_equal(arruma_sa(nao_faz_nada), nao_faz_nada)
})
